- hosts: web
  sudo: yes

  vars:
   - debug:
      OS: "redhat"
      name: "rajesh1"
      age: "33"
      role: "devops1"

  tasks:
  - debug:
     name 
  - name: create group
    group: name=deploy
  - name: Add the user deploy-user
    user:
     name: deploy-user
     group: deploy
  - name: install service httpd
    yum: name=httpd state=present
    when: OS =='redhat'
  - name: start service httpd
    service: name=httpd state=started
  - name: install GIT
    yum: name=git
  - name: install WGET
    yum: name=wget
  - name: createindex.xml file
    blockinfile: dest=/var/www/html/index.html create=yes content=Hello
  - name: clone git repo
    git: repo=https://github.com/scmgalaxy/ansible-role-template dest=/opt/ansible-role-template
