---
- hosts: fullstack
  tasks:
    - name: create a group 'deploy'
      group: name=deploy system=yes
    - name: create and add user deploy-user to deploy group
      user: name=deploy-user groups=deploy append=yes shell=/bin/bash
    - name: install httpd
      yum: name=httpd state=present
    - name: start httpd service
      service: name=httpd state=started
    - name: create index.html
      blockinfile: dest=/var/www/html/index.html create=yes content='<html> <body> Createad </body></html>'
    - name: restart machine
      reboot:
    - name: install git 
      yum:
        pkg: git
        state: present
    - name: pull playbooks from git
      git: repo='https://github.com/scmgalaxy/ansible-role-template' dest='~/ansible-playbook'
...  
