---
- hosts: hosts1
  sudo: yes

  tasks:
  - name: Creating group deploy
    group: name=deploy state=present
  - name: Adding a user to group
    user: name=deploy_user group=deploy
  - name: Ensure that Apache is installed
    apt: name=apache2 state=latest update_cache=yes
  - name: Start Apache Services
    service: name=apache2 enabled=yes state=started
  - name:  Creating a html file 
    file : dest=/var/www/html/index.html state=touch
  - name: Dummy html
    copy : dest=/var/www/html/index.html content='<h1> Hello World </h1>'
  - name : Installing git
    yum : name=git state=latest
  - name : Installing WGet 
    yum : name=wget state=latest
  - name : creating forlder for Repository
    file : dest=/var/www/html/mygitrepo state=directory
  - name : Cloning Repository
    git : dest=/var/www/html/mygitrepo repo=https://github.com/scmgalaxy/ansible-role-template 

...
