---
- hosts: database
  sudo: yes


  tasks:
    - name: Create group
      group: state=present name=group

    - name: Create user
      user: name=usr group=group shell=/bin/bash
    
    - name: install httpd
      yum: name=httpd state=latest
    
    - name: start httpd
      service: name=httpd state=started

    - name: create index.html
      file: path=/var/www/html/index.html state=touch
    
    - name: write to index.html
      copy: dest=/var/www/html/index.html content='Hello'

    - name: install git
      yum: name=git state=latest
    
    - name: clone repo
      git: dest=/home/prakhar/ansible-role-template repo=https://github.com/scmgalaxy/ansible-role-template

...

