- hosts: 127.0.0.1
  tasks:
    - shell: echo "nested test a={{ item[0] }} b={{ item[1] }} c={{ item[2] }}"
      with_nested:
        - [ 'red', 'blue', 'green' ]
        - [ 1, 2, 3 ]
        - [ 'up', 'down', 'strange']
- hosts: 127.0.0.1
  vars:
    listvar1:
      - 'a'
      - 'b'
      - 'c'
  tasks:
    - shell: echo "nested test a={{ item[0] }} b={{ item[1] }}"
      with_nested:
        - listvar1
        - [ 1, 2, 3 ]

