--- 
  - hosts: web
    sudo: yes
    tasks:
      - name: create a group
        group: name=group
      - name: create a user
        user: name=deploy-user group=group shell=/bin/bash
      - name: install httpd, git, wget
        yum:
          name:
            - httpd 
            - git
            - wget
          state: present
      - name: start httpd
        service: name=httpd state=started
      - name: create a file
        blockinfile: dest=/var/www/html/index.html create=yes content='<html><body>Hello</body></html>'
      - name: clone git repo
        git: repo=https://github.com/scmgalaxy/ansible-role-template dest=/opt/ansible-role-template
