---
- hosts: g1
  remote_user: root
  vars:
     this_is_a_regular_var: 'moo'
     so_is_this: 'quack'

  vars_prompt:
    - name: "some_password"
      prompt: "Enter password"
      private: yes

    - name: "release_version"
      prompt: "Product release version"
      default: "my_default_version"
      private: no

    - name: "my_password2"
      prompt: "Enter password2"
      private: yes
      encrypt: "md5_crypt"
      confirm: yes
      salt_size: 7
      salt: "foo"

  tasks:

  - name: imagine this did something interesting with {{release_version}}
    shell: echo foo >> /home/nehakalathia/{{release_version}}-alpha

  - name: look we crypted a password
    debug: 
       msg: "my password is {{ my_password2 }}"


